# Generated by Django 3.1.2 on 2020-12-11 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_title', models.CharField(max_length=500)),
                ('claimant_first_name', models.CharField(max_length=500)),
                ('claimant_last_name', models.CharField(max_length=500)),
                ('claimant_phone_number', models.CharField(max_length=500)),
                ('claimant_policy_number', models.CharField(max_length=500)),
                ('claimant_email', models.CharField(max_length=500)),
                ('claimant_id_number', models.CharField(max_length=500)),
                ('claimant_passport_number', models.CharField(max_length=500)),
                ('claimant_physical_address', models.CharField(max_length=500)),
                ('claimant_postal_address', models.CharField(max_length=500)),
                ('claimant_age', models.CharField(max_length=500)),
                ('claimant_relationship', models.CharField(max_length=500)),
                ('deceased_title', models.CharField(max_length=500)),
                ('deceased_first_name', models.CharField(max_length=500)),
                ('deceased_last_name', models.CharField(max_length=500)),
                ('deceased_date_of_birth', models.CharField(max_length=500)),
                ('deceased_place_of_birth', models.CharField(max_length=500)),
                ('deceased_gender', models.CharField(max_length=500)),
                ('deceased_date_of_death', models.CharField(max_length=500)),
                ('deceased_time_of_death', models.CharField(max_length=500)),
                ('deceased_age_of_death', models.CharField(max_length=500)),
                ('deceased_cause_of_death', models.CharField(max_length=500)),
                ('deceased_place_of_death', models.CharField(max_length=500)),
                ('deceased_passport_number', models.CharField(max_length=500)),
                ('deceased_id_number', models.CharField(max_length=500)),
                ('deceased_marital_status', models.CharField(max_length=500)),
                ('deceased_physical_address', models.CharField(max_length=500)),
                ('deceased_postal_address', models.CharField(max_length=500)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
